### ISSUE TITLE
zstd support

### ISSUE THREAD

**Issue by Vinfall** [yuk7/wsldl#152]
[Zstandard](https://github.com/facebook/zstd) is a loseless compression algorithm, and dual-licensed under [BSD](https://github.com/facebook/zstd/blob/dev/LICENSE) OR [GPLv2](https://github.com/facebook/zstd/blob/dev/COPYING).

WSL supports importing quite a few formats already like `.tar.`, `.tar.xz`, `.tar.gz` and `.tar.zst`.

I'm aware of https://github.com/yuk7/wsldl/issues/109 and agree with the size increase worry. Regarding implementation, do you mean a go package for the compression algorithms or something else? If you mean packages, I think [this](https://pkg.go.dev/github.com/klauspost/compress/zstd) or [this](https://pkg.go.dev/github.com/DataDog/zstd) would work.

To test if it's possible, I just blindly modified https://github.com/yuk7/wsldl/blob/3672589d073871b495efbd11614fa7554455ed7a/src/install/install.go#L20-L22 and gladly importing `.tar.zst` just works. A more thorough support would require importing the package and change https://github.com/yuk7/wsldl/blob/3672589d073871b495efbd11614fa7554455ed7a/src/install/install.go#L106-L124 or wherever I'm unaware of.

A test build of wsldl is available [here](https://github.com/Vinfall/wsldl/releases/tag/24041300) and I successfully built [DevuanWSL](https://github.com/Vinfall/DevuanWSL/releases/tag/20240413-alpha) based on that so it should be feasible I guess.

**Comment by yuk7** [comment]
I'll look into this, thanks.

**Comment by yuk7** [comment]
Ok, I understood.
I'll support it.

**Comment by yuk7** [comment]
I have released a new build that supports tar.zst rootfs.
Please note that this may not be available in users version of WSL.

I will decide later whether to support zstd compression for vhd installs and backups.

**Comment by Vinfall** [comment]
I'll keep this open as it's just partially solved, but personally I use native WSL export and redirecting that to Zstandard works perfectly, thus having no preference on zstd compression support by wsldl.

Code snippet in case anyone is interested:

```powershell
wsl --shutdown
cd path\to\distro
# Make sure to use cmd as PowerShell pipe is known to be problematic
cmd /c "wsl --export Devuan - | zstd -T0 -o Devuan-$(Get-Date -UFormat "%Y%m%d").tar.zst"
```
